
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis_Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINASIG = 13;
  public static final int VV = 55;
  public static final int PLUSPLUS = 9;
  public static final int POR = 54;
  public static final int MI = 58;
  public static final int PUNTO_Y_COMA = 30;
  public static final int LAS = 68;
  public static final int RES = 64;
  public static final int PAROPEN = 24;
  public static final int IMPRIMIR = 44;
  public static final int ADDASIG = 12;
  public static final int ENTERO = 50;
  public static final int SI = 33;
  public static final int NOTEQUAL = 21;
  public static final int MINMIN = 10;
  public static final int SOLS = 67;
  public static final int KEYOPEN = 28;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int COROPEN = 26;
  public static final int idNoVal = 49;
  public static final int SINO = 34;
  public static final int numEntero = 53;
  public static final int OR = 3;
  public static final int MIENTRAS = 31;
  public static final int MIS = 65;
  public static final int DIV = 8;
  public static final int CONTINUAR = 37;
  public static final int IMPORTAR = 35;
  public static final int MIN = 7;
  public static final int ID = 51;
  public static final int DOS = 63;
  public static final int FA = 59;
  public static final int MAYTHAN = 16;
  public static final int EOF = 0;
  public static final int ASIG = 11;
  public static final int LA = 61;
  public static final int RE = 57;
  public static final int EQUAL = 20;
  public static final int error = 1;
  public static final int COMILLA = 22;
  public static final int NULO = 43;
  public static final int MUL = 6;
  public static final int COMA = 23;
  public static final int CADENA = 47;
  public static final int ADD = 5;
  public static final int SILENCIO = 40;
  public static final int MINTHAN = 17;
  public static final int PARCLOSE = 25;
  public static final int MAYEQUAL = 18;
  public static final int ERROR = 52;
  public static final int ROMPER = 36;
  public static final int CORCLOSE = 27;
  public static final int SIS = 69;
  public static final int REPRODUCE = 32;
  public static final int VACIO = 46;
  public static final int MULASIG = 15;
  public static final int NOTA = 45;
  public static final int FRECUENCIA = 39;
  public static final int SII = 62;
  public static final int FAS = 66;
  public static final int SOL = 60;
  public static final int FALSO = 42;
  public static final int VOLUMEN = 38;
  public static final int DIVASIG = 14;
  public static final int BOOLEANO = 70;
  public static final int KEYCLOSE = 29;
  public static final int VERDADERO = 41;
  public static final int INICIO = 48;
  public static final int MINEQUAL = 19;
  public static final int DO = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "ADD",
  "MUL",
  "MIN",
  "DIV",
  "PLUSPLUS",
  "MINMIN",
  "ASIG",
  "ADDASIG",
  "MINASIG",
  "DIVASIG",
  "MULASIG",
  "MAYTHAN",
  "MINTHAN",
  "MAYEQUAL",
  "MINEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "COMILLA",
  "COMA",
  "PAROPEN",
  "PARCLOSE",
  "COROPEN",
  "CORCLOSE",
  "KEYOPEN",
  "KEYCLOSE",
  "PUNTO_Y_COMA",
  "MIENTRAS",
  "REPRODUCE",
  "SI",
  "SINO",
  "IMPORTAR",
  "ROMPER",
  "CONTINUAR",
  "VOLUMEN",
  "FRECUENCIA",
  "SILENCIO",
  "VERDADERO",
  "FALSO",
  "NULO",
  "IMPRIMIR",
  "NOTA",
  "VACIO",
  "CADENA",
  "INICIO",
  "idNoVal",
  "ENTERO",
  "ID",
  "ERROR",
  "numEntero",
  "POR",
  "VV",
  "DO",
  "RE",
  "MI",
  "FA",
  "SOL",
  "LA",
  "SII",
  "DOS",
  "RES",
  "MIS",
  "FAS",
  "SOLS",
  "LAS",
  "SIS",
  "BOOLEANO"
  };
}

