/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miscelaneos.Renders;

import Analisis_Lexico.EstiloDocumento;
import Archivos.Archivos;
import Miscelaneos.Miscelaneo;
import Ventanas.Inicio;
import java.awt.Font;
import java.awt.TextArea;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.text.Style;
import javax.swing.text.StyledDocument;

/**
 *
 * @author edgar
 */
public class Render_Item extends javax.swing.JPanel {
    
    private StyledDocument doc;
    private Style style;
    /**
     * Creates new form Render_Item
     */
    public Render_Item(Archivos ar,Tab tab,Inicio inicio) {
        initComponents();
        this.archivo=ar;
        this.inicio=inicio;
        this.tab=tab;
        
        doc = new EstiloDocumento(txt_contenido);
        txt_contenido.requestFocus();
        txt_contenido.setDocument(doc);
        
        style = txt_contenido.addStyle("I'm a Style", null);
        
        this.txt_contenido.setText(archivo.contenido);
        
        Miscelaneo.actualizar_numeros(this.txt_numeros, archivo,true);
        this.scroll_numeros.getVerticalScrollBar().setModel(this.scroll_texto.getVerticalScrollBar().getModel());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll_numeros = new javax.swing.JScrollPane();
        txt_numeros = new javax.swing.JTextArea();
        scroll_texto = new javax.swing.JScrollPane();
        txt_contenido = new javax.swing.JTextPane();

        scroll_numeros.setBorder(null);
        scroll_numeros.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll_numeros.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_numeros.setEditable(false);
        txt_numeros.setBackground(getBackground());
        txt_numeros.setColumns(1);
        txt_numeros.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        txt_numeros.setForeground(new java.awt.Color(102, 102, 102));
        txt_numeros.setRows(8);
        scroll_numeros.setViewportView(txt_numeros);

        txt_contenido.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        txt_contenido.setToolTipText("");
        txt_contenido.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txt_contenido.setMinimumSize(new java.awt.Dimension(4, 20));
        txt_contenido.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_contenidoCaretUpdate(evt);
            }
        });
        scroll_texto.setViewportView(txt_contenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(scroll_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_texto)
                    .addComponent(scroll_numeros, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contenidoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_contenidoCaretUpdate
        archivo.contenido=this.txt_contenido.getText();
        archivo.cambios=true;
        inicio.archivo_seleccionado=archivo;
        Miscelaneo.actualizar_numeros(txt_numeros, archivo,false);
    }//GEN-LAST:event_txt_contenidoCaretUpdate
    
    public Archivos archivo;
    public Tab tab;
    public Inicio inicio;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll_numeros;
    private javax.swing.JScrollPane scroll_texto;
    private javax.swing.JTextPane txt_contenido;
    private javax.swing.JTextArea txt_numeros;
    // End of variables declaration//GEN-END:variables
}
