/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author willi
 */
public class MostrarTablas extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public MostrarTablas() {
        initComponents();
        this.setLocationRelativeTo(this);
        Image i = null;
        try {
            i = ImageIO.read(getClass().getResource("/Imagenes/music.png"));
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(i);
        this.getContentPane().setBackground(new Color(255, 203, 87));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOptimizado = new javax.swing.JTabbedPane();
        panelAutomata = new javax.swing.JPanel();
        panelArbol = new javax.swing.JPanel();
        panelGramatica = new javax.swing.JPanel();
        jScrollPane_Gramatica = new javax.swing.JScrollPane();
        jTextPane_Gramatica = new javax.swing.JTextPane();
        panelIntermedio = new javax.swing.JPanel();
        jScrollPane_intermedio = new javax.swing.JScrollPane();
        textPane_Intermedio = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane_optimizado = new javax.swing.JScrollPane();
        textPane_Optimizado = new javax.swing.JTextPane();
        panelMaquina = new javax.swing.JPanel();
        jScrollPane_maquina = new javax.swing.JScrollPane();
        textPane_Maquina = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Miscelaneos");
        setBackground(new java.awt.Color(255, 203, 87));

        panelAutomata.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout panelAutomataLayout = new javax.swing.GroupLayout(panelAutomata);
        panelAutomata.setLayout(panelAutomataLayout);
        panelAutomataLayout.setHorizontalGroup(
            panelAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        panelAutomataLayout.setVerticalGroup(
            panelAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        panelOptimizado.addTab("Autómata Finito", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/automata.png")), panelAutomata); // NOI18N

        panelArbol.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout panelArbolLayout = new javax.swing.GroupLayout(panelArbol);
        panelArbol.setLayout(panelArbolLayout);
        panelArbolLayout.setHorizontalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        panelArbolLayout.setVerticalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        panelOptimizado.addTab("Arbol de expresiones", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sitemap_1.png")), panelArbol); // NOI18N
        panelArbol.getAccessibleContext().setAccessibleName("");

        panelGramatica.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane_Gramatica.setViewportView(jTextPane_Gramatica);

        javax.swing.GroupLayout panelGramaticaLayout = new javax.swing.GroupLayout(panelGramatica);
        panelGramatica.setLayout(panelGramaticaLayout);
        panelGramaticaLayout.setHorizontalGroup(
            panelGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGramaticaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane_Gramatica, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        panelGramaticaLayout.setVerticalGroup(
            panelGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGramaticaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane_Gramatica, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        panelOptimizado.addTab("Gramática", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil.png")), panelGramatica); // NOI18N

        panelIntermedio.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane_intermedio.setViewportView(textPane_Intermedio);

        javax.swing.GroupLayout panelIntermedioLayout = new javax.swing.GroupLayout(panelIntermedio);
        panelIntermedio.setLayout(panelIntermedioLayout);
        panelIntermedioLayout.setHorizontalGroup(
            panelIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIntermedioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane_intermedio, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        panelIntermedioLayout.setVerticalGroup(
            panelIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIntermedioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane_intermedio, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        panelOptimizado.addTab("Código Intermedio", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intermedio.png")), panelIntermedio); // NOI18N

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane_optimizado.setViewportView(textPane_Optimizado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane_optimizado, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane_optimizado, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOptimizado.addTab("Código Optimizado", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search-engine-optimization.png")), jPanel3); // NOI18N

        panelMaquina.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane_maquina.setViewportView(textPane_Maquina);

        javax.swing.GroupLayout panelMaquinaLayout = new javax.swing.GroupLayout(panelMaquina);
        panelMaquina.setLayout(panelMaquinaLayout);
        panelMaquinaLayout.setHorizontalGroup(
            panelMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaquinaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane_maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        panelMaquinaLayout.setVerticalGroup(
            panelMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaquinaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane_maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOptimizado.addTab("Código Máquina", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binary-code.png")), panelMaquina); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOptimizado)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOptimizado)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane_Gramatica;
    public javax.swing.JScrollPane jScrollPane_intermedio;
    public javax.swing.JScrollPane jScrollPane_maquina;
    public javax.swing.JScrollPane jScrollPane_optimizado;
    public javax.swing.JTextPane jTextPane_Gramatica;
    public javax.swing.JPanel panelArbol;
    public javax.swing.JPanel panelAutomata;
    public javax.swing.JPanel panelGramatica;
    public javax.swing.JPanel panelIntermedio;
    private javax.swing.JPanel panelMaquina;
    public javax.swing.JTabbedPane panelOptimizado;
    public javax.swing.JTextPane textPane_Intermedio;
    public javax.swing.JTextPane textPane_Maquina;
    public javax.swing.JTextPane textPane_Optimizado;
    // End of variables declaration//GEN-END:variables
}
