/* The following code was generated by JFlex 1.7.0 */

package Analisis_Lexico;

/* --------------------------Codigo de Usuario----------------------- */


import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>./src/Analisis_Lexico/Lexer.jflex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\6\1\7\1\7\1\5\22\0\1\4\1\17\1\16"+
    "\1\13\2\0\1\14\1\25\1\27\1\30\1\11\1\20\1\26\1\21"+
    "\1\3\1\10\12\2\1\3\1\35\1\24\1\22\1\23\1\3\1\15"+
    "\1\65\2\1\1\56\1\61\1\64\2\1\1\63\2\1\1\67\1\62"+
    "\1\1\1\57\2\1\1\60\1\66\7\1\1\31\1\0\1\32\1\3"+
    "\1\1\1\3\1\46\1\1\1\40\1\51\1\43\1\55\2\1\1\36"+
    "\2\1\1\54\1\42\1\37\1\41\1\50\1\1\1\45\1\47\1\44"+
    "\1\52\1\53\4\1\1\33\1\12\1\34\1\3\6\0\1\7\33\0"+
    "\1\3\6\0\1\3\6\0\1\3\1\3\3\0\1\3\12\0\1\3"+
    "\1\3\1\3\1\0\1\3\1\3\2\0\1\3\1\3\1\3\1\0"+
    "\1\3\1\3\1\3\3\0\1\3\1\3\2\0\1\3\1\3\2\0"+
    "\1\3\1\3\1\0\1\3\3\0\1\3\1\3\1\0\1\3\1\3"+
    "\2\0\1\3\1\3\1\3\1\0\1\3\1\3\1\3\1\0\1\3"+
    "\1\0\1\3\1\3\1\3\1\0\1\3\1\3\2\0\1\3\1\3"+
    "\1\0\1\3\u1f2b\0\1\7\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\1\1\5\1\6\1\7"+
    "\1\10\1\11\1\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\20\3\1\1\1\31\1\5\1\0\1\32"+
    "\1\33\4\0\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\12\3\1\45\6\3\1\46\1\47"+
    "\1\50\1\51\1\3\1\52\1\53\1\0\1\5\3\0"+
    "\14\3\1\54\5\3\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\1\63\1\0\1\5\1\0\3\3\1\64\1\65"+
    "\6\3\1\66\6\3\1\67\1\0\14\3\1\70\1\3"+
    "\1\71\1\0\1\72\3\3\1\73\1\3\1\74\1\75"+
    "\5\3\1\0\6\3\1\76\2\3\1\77\1\100\1\3"+
    "\1\101\1\3\1\102\2\3\1\103\1\104\1\105\1\3"+
    "\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\70\0\u0118\0\u0150"+
    "\0\u0188\0\70\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460"+
    "\0\u0498\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620"+
    "\0\u0658\0\u0690\0\u0188\0\u06c8\0\u0700\0\u0738\0\70\0\70"+
    "\0\u0770\0\u07a8\0\u01c0\0\u07e0\0\u01c0\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\u0818\0\u0850\0\u0888"+
    "\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08"+
    "\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0700\0\u0d58\0\u0d90"+
    "\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50"+
    "\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\160\0\u10d8"+
    "\0\u1110\0\u1148\0\u1180\0\u11b8\0\70\0\70\0\70\0\70"+
    "\0\u11f0\0\70\0\70\0\u1228\0\u0d90\0\u1260\0\u1298\0\u12d0"+
    "\0\u1308\0\160\0\160\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420"+
    "\0\u1458\0\160\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\u15a8"+
    "\0\70\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\160\0\u18b8"+
    "\0\160\0\u18f0\0\160\0\u1928\0\u1960\0\u1998\0\160\0\u19d0"+
    "\0\160\0\160\0\u1a08\0\u1a40\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20"+
    "\0\u1b58\0\u1b90\0\u1bc8\0\u1c00\0\u1c38\0\u1c70\0\160\0\u1ca8"+
    "\0\u1ce0\0\160\0\160\0\u1d18\0\160\0\u1d50\0\160\0\u1d88"+
    "\0\u1dc0\0\160\0\160\0\160\0\u1df8\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\3\6\1\0\1\7\1\10"+
    "\1\11\1\2\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\3"+
    "\1\36\1\37\1\3\1\40\1\3\1\41\1\42\2\3"+
    "\1\43\1\3\1\44\1\45\1\3\1\46\1\3\1\47"+
    "\1\3\1\50\1\3\1\51\1\52\71\0\2\3\1\5"+
    "\6\0\1\53\23\0\32\3\1\0\1\54\1\4\1\5"+
    "\6\0\1\53\23\0\32\54\1\0\3\5\6\0\1\53"+
    "\23\0\32\5\10\0\1\55\1\56\10\0\1\57\67\0"+
    "\1\60\45\0\1\61\3\53\6\61\1\53\1\62\22\61"+
    "\32\53\11\63\1\64\4\63\1\65\51\63\22\0\1\66"+
    "\65\0\1\67\1\0\1\70\66\0\1\71\1\72\67\0"+
    "\1\73\67\0\1\74\67\0\1\75\46\0\2\3\1\5"+
    "\6\0\1\53\23\0\1\3\1\76\2\3\1\77\25\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\3\3\1\100"+
    "\10\3\1\101\15\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\3\3\1\102\4\3\1\103\21\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\1\104\31\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\1\3\1\105\30\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\3\3\1\106\1\3"+
    "\1\107\24\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\1\110\31\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\3\3\1\111\26\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\3\3\1\112\1\3\1\113\2\3\1\114\21\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\7\3\1\115"+
    "\1\116\21\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\21\3\1\117\10\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\23\3\1\120\6\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\25\3\1\121\4\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\27\3\1\122\2\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\21\3\1\123\3\3\1\124"+
    "\4\3\1\0\2\3\1\5\6\0\1\53\23\0\27\3"+
    "\1\125\2\3\1\0\2\54\1\5\6\0\1\53\23\0"+
    "\32\54\5\126\1\127\1\6\61\126\11\130\1\131\56\130"+
    "\13\61\1\62\66\61\1\132\1\62\54\61\10\63\1\0"+
    "\1\64\56\63\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\1\133\31\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\12\3\1\134\17\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\6\3\1\135\23\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\16\3\1\136\13\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\1\3\1\137\30\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\13\3\1\140\16\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\5\3\1\141\24\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\6\3\1\142"+
    "\23\3\1\0\2\3\1\5\6\0\1\53\23\0\4\3"+
    "\1\143\25\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\12\3\1\144\17\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\1\3\1\145\14\3\1\146\13\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\7\3\1\147\22\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\16\3\1\150\13\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\7\3\1\151"+
    "\22\3\1\0\2\3\1\5\6\0\1\53\23\0\2\3"+
    "\1\152\27\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\5\3\1\153\24\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\16\3\1\154\13\3\1\0\2\3\1\5\6\0"+
    "\1\53\12\0\1\155\10\0\32\3\1\0\2\3\1\5"+
    "\6\0\1\53\12\0\1\156\10\0\32\3\1\0\2\3"+
    "\1\5\6\0\1\53\12\0\1\157\10\0\32\3\1\0"+
    "\2\3\1\5\6\0\1\53\12\0\1\160\10\0\32\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\31\3\1\161"+
    "\1\0\2\3\1\5\6\0\1\53\12\0\1\162\10\0"+
    "\32\3\1\0\2\3\1\5\6\0\1\53\12\0\1\163"+
    "\10\0\32\3\6\0\1\6\61\0\11\130\1\164\66\130"+
    "\1\165\1\164\56\130\13\61\1\62\1\166\53\61\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\2\3\1\167\27\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\3\3\1\170"+
    "\3\3\1\171\22\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\10\3\1\172\21\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\3\3\1\173\26\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\6\3\1\174\23\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\5\3\1\175\24\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\1\3\1\176\30\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\5\3\1\177"+
    "\24\3\1\0\2\3\1\5\6\0\1\53\23\0\12\3"+
    "\1\200\17\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\7\3\1\201\22\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\3\3\1\202\26\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\5\3\1\203\24\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\14\3\1\204\15\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\13\3\1\205\16\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\1\206\31\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\2\3\1\207\27\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\11\3\1\210"+
    "\20\3\1\0\2\3\1\5\6\0\1\53\12\0\1\211"+
    "\10\0\32\3\10\130\1\6\1\164\56\130\12\61\1\212"+
    "\1\62\54\61\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\1\213\31\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\7\3\1\214\22\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\1\215\31\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\1\216\31\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\1\3\1\217\30\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\6\3\1\220\23\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\7\3\1\221\22\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\5\3\1\222\24\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\3\3\1\223\26\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\1\3\1\224"+
    "\30\3\1\0\2\3\1\5\6\0\1\53\23\0\4\3"+
    "\1\225\25\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\10\3\1\226\21\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\3\3\1\227\26\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\14\3\1\230\15\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\3\3\1\231\26\3\13\61\1\62"+
    "\1\61\1\232\52\61\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\3\3\1\233\26\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\6\3\1\234\23\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\4\3\1\235\25\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\1\3\1\236\30\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\10\3\1\237\21\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\7\3\1\240"+
    "\22\3\1\0\2\3\1\5\6\0\1\53\23\0\3\3"+
    "\1\241\26\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\7\3\1\242\22\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\13\3\1\243\16\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\2\3\1\244\27\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\5\3\1\245\24\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\13\3\1\246\16\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\5\3\1\247\24\3"+
    "\12\61\1\250\1\62\54\61\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\10\3\1\251\21\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\1\252\31\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\14\3\1\253\15\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\10\3\1\254\21\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\14\3\1\255\15\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\1\256\31\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\1\3\1\257"+
    "\30\3\1\0\2\3\1\5\6\0\1\53\23\0\5\3"+
    "\1\260\24\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\1\3\1\261\30\3\13\61\1\62\2\61\1\53\51\61"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\7\3\1\262"+
    "\22\3\1\0\2\3\1\5\6\0\1\53\23\0\7\3"+
    "\1\263\22\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\10\3\1\264\21\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\11\3\1\265\20\3\1\0\2\3\1\5\6\0"+
    "\1\53\23\0\2\3\1\266\27\3\1\0\2\3\1\5"+
    "\6\0\1\53\23\0\3\3\1\267\26\3\1\0\2\3"+
    "\1\5\6\0\1\53\23\0\7\3\1\270\22\3\1\0"+
    "\2\3\1\5\6\0\1\53\23\0\2\3\1\271\27\3"+
    "\1\0\2\3\1\5\6\0\1\53\23\0\7\3\1\272"+
    "\22\3\1\0\2\3\1\5\6\0\1\53\23\0\5\3"+
    "\1\273\24\3\1\0\2\3\1\5\6\0\1\53\23\0"+
    "\3\3\1\274\26\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\1\275\31\3\1\0\2\3\1\5\6\0\1\53"+
    "\23\0\10\3\1\276\21\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7728];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\3\1\1\11\7\1\11\11"+
    "\23\1\1\0\2\11\4\0\1\1\10\11\30\1\1\0"+
    "\1\1\3\0\22\1\4\11\1\1\2\11\1\0\1\1"+
    "\1\0\22\1\1\11\1\0\17\1\1\0\15\1\1\0"+
    "\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /*  Generamos un java_cup.Symbol para guardar el tipo de token 
        encontrado */
    public Symbol symbol(int type) {
        return new Symbol(type, yyline+1, columna+1);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado 
       junto con su valor */
    public Symbol symbol(int type,Object value) {
        
        return new Symbol(type, yyline+1, columna+1, value);
    }
    public int linea,columna;
    public String lexeme,cadena;
    public String comp;
Pintar_Palabras pintar = new Pintar_Palabras();



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 324) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { try { lexeme=yytext(); comp="ERROR"; return new Symbol(sym.ERROR, yychar,yyline,yytext()); } catch(Exception e) { lexeme=yytext(); comp="idNoVal"; return new Symbol(sym.idNoVal, yychar,yyline,yytext()); }
            } 
            // fall through
          case 71: break;
          case 2: 
            { try { lexeme=yytext(); comp="ERROR"; return new Symbol(sym.ERROR, yychar,yyline); } catch(Exception e) { lexeme=yytext(); comp="idNoVal"; return new Symbol(sym.idNoVal, yychar,yyline ,yytext()); }
            } 
            // fall through
          case 72: break;
          case 3: 
            { lexeme=yytext();comp="ID"; return new Symbol(sym.ID, yychar,yyline,yytext());
            } 
            // fall through
          case 73: break;
          case 4: 
            { lexeme=yytext();comp="numEntero"; return new Symbol(sym.numEntero, yychar,yyline,yytext());
            } 
            // fall through
          case 74: break;
          case 5: 
            { /*Ignore*/
            } 
            // fall through
          case 75: break;
          case 6: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.DIV, yychar,yyline,yytext());
            } 
            // fall through
          case 76: break;
          case 7: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.MUL, yychar,yyline,yytext());
            } 
            // fall through
          case 77: break;
          case 8: 
            { lexeme=yytext(); comp="LOGICO"; return new Symbol(sym.OR, yychar,yyline,yytext());
            } 
            // fall through
          case 78: break;
          case 9: 
            { lexeme=yytext(); comp="LOGICO"; return new Symbol(sym.AND, yychar,yyline,yytext());
            } 
            // fall through
          case 79: break;
          case 10: 
            { lexeme=yytext(); comp="LOGICO"; return new Symbol(sym.NOT, yychar,yyline,yytext());
            } 
            // fall through
          case 80: break;
          case 11: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.ADD, yychar,yyline,yytext());
            } 
            // fall through
          case 81: break;
          case 12: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.MIN, yychar,yyline,yytext());
            } 
            // fall through
          case 82: break;
          case 13: 
            { lexeme=yytext(); comp="ASSIGNACION"; return new Symbol(sym.ASIG, yychar,yyline,yytext());
            } 
            // fall through
          case 83: break;
          case 14: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.MAYTHAN, yychar,yyline,yytext());
            } 
            // fall through
          case 84: break;
          case 15: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.MINTHAN, yychar,yyline,yytext());
            } 
            // fall through
          case 85: break;
          case 16: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.COMILLA, yychar,yyline,"'");
            } 
            // fall through
          case 86: break;
          case 17: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.COMA, yychar,yyline,",");
            } 
            // fall through
          case 87: break;
          case 18: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.PAROPEN, yychar,yyline,"(");
            } 
            // fall through
          case 88: break;
          case 19: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.PARCLOSE, yychar,yyline,")");
            } 
            // fall through
          case 89: break;
          case 20: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.COROPEN, yychar,yyline,"[");
            } 
            // fall through
          case 90: break;
          case 21: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.CORCLOSE, yychar,yyline,"]");
            } 
            // fall through
          case 91: break;
          case 22: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.KEYOPEN, yychar,yyline,"{");
            } 
            // fall through
          case 92: break;
          case 23: 
            { lexeme=yytext(); comp="AGRUPACION"; return new Symbol(sym.KEYCLOSE, yychar,yyline,"}");
            } 
            // fall through
          case 93: break;
          case 24: 
            { lexeme=yytext(); comp="PUNTO_Y_COMA"; return new Symbol(sym.PUNTO_Y_COMA, yychar,yyline,yytext());
            } 
            // fall through
          case 94: break;
          case 25: 
            { lexeme=yytext();comp="idNoVal"; return new Symbol(sym.idNoVal, yychar,yyline,yytext());
            } 
            // fall through
          case 95: break;
          case 26: 
            { lexeme=yytext(); comp="ASSIGNACION"; return new Symbol(sym.DIVASIG, yychar,yyline,yytext());
            } 
            // fall through
          case 96: break;
          case 27: 
            { lexeme=yytext(); comp="ASSIGNACION"; return new Symbol(sym.MULASIG, yychar,yyline,yytext());
            } 
            // fall through
          case 97: break;
          case 28: 
            { pintar.pintaNara(yychar,yylength());lexeme=yytext(); return new Symbol(sym.CADENA, yychar,yyline,yytext());
            } 
            // fall through
          case 98: break;
          case 29: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.NOTEQUAL, yychar,yyline,yytext());
            } 
            // fall through
          case 99: break;
          case 30: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.PLUSPLUS, yychar,yyline,yytext());
            } 
            // fall through
          case 100: break;
          case 31: 
            { lexeme=yytext(); comp="ASSIGNACION"; return new Symbol(sym.ADDASIG, yychar,yyline,yytext());
            } 
            // fall through
          case 101: break;
          case 32: 
            { lexeme=yytext(); comp="ARITMETICO"; return new Symbol(sym.MINMIN, yychar,yyline,yytext());
            } 
            // fall through
          case 102: break;
          case 33: 
            { lexeme=yytext(); comp="ASSIGNACION"; return new Symbol(sym.MINASIG, yychar,yyline,yytext());
            } 
            // fall through
          case 103: break;
          case 34: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.EQUAL, yychar,yyline,yytext());
            } 
            // fall through
          case 104: break;
          case 35: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.MAYEQUAL, yychar,yyline,yytext());
            } 
            // fall through
          case 105: break;
          case 36: 
            { lexeme=yytext(); comp="RELACIONAL"; return new Symbol(sym.MINEQUAL, yychar,yyline,yytext());
            } 
            // fall through
          case 106: break;
          case 37: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.SI, yychar,yyline,"si");
            } 
            // fall through
          case 107: break;
          case 38: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.DO, yychar,yyline,"DO");
            } 
            // fall through
          case 108: break;
          case 39: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.RE, yychar,yyline,"RE");
            } 
            // fall through
          case 109: break;
          case 40: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.MI, yychar,yyline,"MI");
            } 
            // fall through
          case 110: break;
          case 41: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.FA, yychar,yyline,"FA");
            } 
            // fall through
          case 111: break;
          case 42: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.SII, yychar,yyline,"SII");
            } 
            // fall through
          case 112: break;
          case 43: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.LA, yychar,yyline,"LA");
            } 
            // fall through
          case 113: break;
          case 44: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.POR, yychar,yyline,"por");
            } 
            // fall through
          case 114: break;
          case 45: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.DOS, yychar,yyline,"DO'");
            } 
            // fall through
          case 115: break;
          case 46: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.RES, yychar,yyline,"RE'");
            } 
            // fall through
          case 116: break;
          case 47: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.MIS, yychar,yyline,"MI'");
            } 
            // fall through
          case 117: break;
          case 48: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.FAS, yychar,yyline,"FA'");
            } 
            // fall through
          case 118: break;
          case 49: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.SOL, yychar,yyline,"SOL");
            } 
            // fall through
          case 119: break;
          case 50: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.SIS, yychar,yyline,"SI'");
            } 
            // fall through
          case 120: break;
          case 51: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.LAS, yychar,yyline,"LA'");
            } 
            // fall through
          case 121: break;
          case 52: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.NOTA, yychar,yyline,"nota");
            } 
            // fall through
          case 122: break;
          case 53: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.NULO, yychar,yyline,"nulo");
            } 
            // fall through
          case 123: break;
          case 54: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.SINO, yychar,yyline,"sino");
            } 
            // fall through
          case 124: break;
          case 55: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.SOLS, yychar,yyline,"SOL'");
            } 
            // fall through
          case 125: break;
          case 56: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.VACIO, yychar,yyline,"vacio");
            } 
            // fall through
          case 126: break;
          case 57: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.FALSO, yychar,yyline,"falso");
            } 
            // fall through
          case 127: break;
          case 58: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.INICIO, yychar,yyline,"inicio");
            } 
            // fall through
          case 128: break;
          case 59: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.CADENA, yychar,yyline,"cadena");
            } 
            // fall through
          case 129: break;
          case 60: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.ENTERO, yychar,yyline,"entero");
            } 
            // fall through
          case 130: break;
          case 61: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.ROMPER, yychar,yyline,"romper");
            } 
            // fall through
          case 131: break;
          case 62: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.VOLUMEN, yychar,yyline,"volumen");
            } 
            // fall through
          case 132: break;
          case 63: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.IMPORTAR, yychar,yyline,"importar");
            } 
            // fall through
          case 133: break;
          case 64: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.IMPRIMIR, yychar,yyline,"imprimir");
            } 
            // fall through
          case 134: break;
          case 65: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.MIENTRAS, yychar,yyline,"mientras");
            } 
            // fall through
          case 135: break;
          case 66: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.SILENCIO, yychar,yyline,"silencio");
            } 
            // fall through
          case 136: break;
          case 67: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.CONTINUAR, yychar,yyline,"continuar");
            } 
            // fall through
          case 137: break;
          case 68: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext(); comp="PALABRA_RESERVADA";return new Symbol(sym.REPRODUCE, yychar,yyline,"reproduce");
            } 
            // fall through
          case 138: break;
          case 69: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.VERDADERO, yychar,yyline,"verdadero");
            } 
            // fall through
          case 139: break;
          case 70: 
            { pintar.pintaAzul(yychar,yylength()); lexeme=yytext();comp="PALABRA_RESERVADA";return new Symbol(sym.FRECUENCIA, yychar,yyline,"frecuencia");
            } 
            // fall through
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
